version: "3"
services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DBUSERNAME=postgres
      - DBPASSWORD=postgres
      - DBHOST=db
      - DBDATABASE=postgres
      - MLFLOW_ARTIFACT_S3_URI=/var/mlflow/mlruns
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./mlruns:/var/mlflow/mlruns
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
volumes:
  db-data:
